name       : glew
version    : 1.12.0
release    : 1
source     :
    - http://jaist.dl.sourceforge.net/project/glew/glew/1.12.0/glew-1.12.0.tgz : af58103f4824b443e7fa4ed3af593b8edac6f3a7be3b30911edbc7344f48e4bf
license    :
    - GPL-2.0
    - MIT
    - BSD-3-Clause
summary    : OpenGL Extension Wrangler Library
description: |
    OpenGL Extension Wrangler Library
builddeps  :
    - pkgconfig(xmu)
    - pkgconfig(xi)
    - pkgconfig(glu)
build      : |
    %make
install    : |
    %make_install
