name       : glew
version    : 1.12.0
release    : 1
source     :
    - https://github.com/nigels-com/glew/archive/glew-1.12.0.tar.gz : 8da26b0b9eb19e95bc7d7cbeb3d22c77d147a8d5b3143f41545a70549ef5d6d3
license    :
    - GPL-2.0
    - MIT
    - BSD-3-Clause
summary    : OpenGL Extension Wrangler Library
description: |
    OpenGL Extension Wrangler Library
builddeps  :
build      : |
    %make
install    : |
    %make_install
