name       : glew
version    : 2.1.0
release    : 6
source     :
    - https://jaist.dl.sourceforge.net/project/glew/glew/2.1.0/glew-2.1.0.tgz : 04de91e7e6763039bc11940095cd9c7f880baba82196a7765f727ac05a993c95
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - MIT
component  : desktop.library
summary    : OpenGL Extension Wrangler Library
description: |
    The OpenGL Extension Wrangler Library (GLEW) is a cross-platform C/C++
    extension loading library. GLEW provides efficient run-time mechanisms for
    determining which OpenGL extensions are supported on the target platform.
    OpenGL core and extension functionality is exposed in a single header file.
builddeps  :
    - pkgconfig32(glu)
    - pkgconfig32(x11)
    - pkgconfig32(xi)
    - pkgconfig32(xmu)
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/glew-2.0.0-install-headers.patch
build      : |
    ARCH64="false"
    if [[ -z "${EMUL32BUILD}" ]]; then
        ARCH64="true"
    fi

    %make CC="${CC}" LD="${CC}" ALIBDIR="lib%LIBSUFFIX%" ARCH64="${ARCH64}"
install    : |
    make install.all DESTDIR=%installroot% LIBDIR=%libdir% PKGDIR=%libdir%/pkgconfig

    rm -vf "$installdir"/%libdir%/*.a
