name       : glew
version    : 1.12.0
release    : 5
source     :
    - http://jaist.dl.sourceforge.net/project/glew/glew/1.12.0/glew-1.12.0.tgz : af58103f4824b443e7fa4ed3af593b8edac6f3a7be3b30911edbc7344f48e4bf
license    :
    - GPL-2.0
    - MIT
    - BSD-3-Clause
summary    : OpenGL Extension Wrangler Library
description: |
    OpenGL Extension Wrangler Library
builddeps  :
    - pkgconfig(xmu)
    - pkgconfig32(xmu)
    - pkgconfig(xi)
    - pkgconfig32(xi)
    - pkgconfig(glu)
    - pkgconfig32(glu)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/0001-Underp-buildsystem.patch
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        libdir="lib32"
        ARCH64="false"
    else
        libdir="lib64"
        ARCH64="true"
    fi
    %make CC="${CC}" LD="${CC}" ALIBDIR="${libdir}" ARCH64="${ARCH64}"
install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        libdir="lib32"
        ARCH64="false"
    else
        libdir="lib64"
        ARCH64="true"
    fi
    %make_install CC="${CC}" LD="${CC}" ALIBDIR="${libdir}" ARCH64="${ARCH64}"
    rm -vf "$installdir"/%libdir%/*.a
